### PR TITLE
Added new Section Pages

### PR DESCRIPTION
**Pull request by Deathrow77**

### CODE REVIEW

**Comment by divyanshumehta** [comment]
@arnav-amb Plz review and merge ASAP

**Comment by devanshgoenka97** [comment]
@divyanshumehta No merge conflicts here, so should I merge?

**Comment by divyanshumehta** [comment]
@arnav-amb your call, I can't mess with the design he has in mind

**Comment by arnav-amb** [comment]
@Dea

**Comment by arnav-amb** [comment]
@Dea

**Comment by arnav-amb** [comment]
We can resolve these merge conflicts tonight. @Deathrow77 please come. :-)

**Pull request closed without merging**
