### PR TITLE
landing page initial commit

### PR DESCRIPTION
**Pull request by arnav-amb**

### CODE REVIEW

**Comment by Compro-Prasad** [comment]
Can you post a screenshot?

**Comment by Compro-Prasad** [comment]
What if footer is removed. Because it was a design decision proposed Sir.

**Comment by modihere** [comment]
footer has to be there

**Comment by modihere** [comment]
sir has told

**Comment by Compro-Prasad** [comment]
Yes. But there should be logos of things like `Digital India` and stuff. No text.

**Pull request closed without merging**
